language: ruby
rvm:
  - 2.2.5
  - 2.3.0
env:
  - DB=sqlite
  - DB=postgresql
before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - mysql -e 'create database smithycms_test'
  - psql -c 'create database smithycms_test' -U postgres
