sqlite: &sqlite
  adapter: sqlite3
  database: ":memory:"

mysql: &mysql
  adapter: mysql2
  database: smithycms_<%= Rails.env %>
  username: travis
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  database: smithycms_<%= Rails.env %>
  username: postgres
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
