sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  database: smithycms_<%= Rails.env %>
  username: root
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  database: smithycms_<%= Rails.env %>
  username: tim
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
