# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc37d0e2f3d93ee328e70a1d4a708f7c9ed5b1f7369cd67cac3ecd1dde17d5e8ea5e2739f01b10628b5906f13ecd4a9a7c0232351d2063e04f8dc5548df45bc4

test:
  secret_key_base: 35b240e6c63c625bc09bb19b50be49d1326b52d4b164b7267f7e3206376d869ef90397480a1584f7cad9c1ed0ef81f2b6604123c227c3e9f1eda3b7d3c1e59ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
